import fastapi
import uvicorn
from gemini import recommendation_system
from api import get_forecast_stress, get_historical_data
from fastapi.middleware.cors import CORSMiddleware
from datetime import date

app = fastapi.FastAPI()
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Allow only specific origins
    allow_credentials=True,
    allow_methods=["*"],  # Allow all methods (GET, POST, etc.)
    allow_headers=["*"],  # Allow all headers
)

@app.get("/risks")
def get_risks(lat: float, lon: float, crop: str):
    """
    Get risk factors for a given location and crop.

    Parameters:
        lat (float): Latitude coordinate.
        lon (float): Longitude coordinate.
        crop (str): Name of the crop.

    Returns:
        dict: A dictionary containing various risk indices.
    """
    return get_historical_data(lat, lon, crop)


@app.get("/recommendations")
def get_recommendations(lat: float, lon: float, crop: str):
    """
    Retrieve crop recommendations based on geographical coordinates.

    Parameters:
        lat (float): Latitude coordinate.
        lon (float): Longitude coordinate.
        crop (str): Name of the crop.

    Returns:
        dict: Recommendations generated by the recommendation system.
    """
    return recommendation_system(crop, lat, lon)


@app.get("/results")
def get_results(lat: float, lon: float, crop: str):
    """
    Obtain result data for a given location and crop.

    Parameters:
        lat (float): Latitude coordinate.
        lon (float): Longitude coordinate.
        crop (str): Name of the crop.

    Returns:
        dict: An empty dictionary currently serving as a placeholder for future results.
    """
    return {}


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
